### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by bonfus** [positivemuon/aiida-muon#1]
Ciao @ionuorah, why is the element searched in U_dict1 but collected from U_dict2?

https://github.com/positivemuon/aiida-muon/blob/ed94553f6cfba63dd032515be895c826d6eb7f56/aiida_muon/workflows/utils.py#L134C24-L134C31

Is this a typo? Can I change this?

**Comment by ionuorah** [comment]
Yes, it is a typo, have to be corrected. Also, I was not sure which of them to use. U_dict1 or U_dict2

**Comment by bonfus** [comment]
This has been solved in commit aa7c81c .
